// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpHMx6fsU4HdCHD-f8m3BKi5CFRALNRQ0',
    appId: '1:805174990201:web:3240c859f66fee8d734ba8',
    messagingSenderId: '805174990201',
    projectId: 'multiplayer-tictactoe-c4744',
    authDomain: 'multiplayer-tictactoe-c4744.firebaseapp.com',
    storageBucket: 'multiplayer-tictactoe-c4744.firebasestorage.app',
    measurementId: 'G-JX7MXL65SV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFU-rLk8xHVM3w-8gVv8LFzZyQduppqsc',
    appId: '1:805174990201:ios:95e8d1d92e2a4824734ba8',
    messagingSenderId: '805174990201',
    projectId: 'multiplayer-tictactoe-c4744',
    storageBucket: 'multiplayer-tictactoe-c4744.firebasestorage.app',
    iosClientId: '805174990201-tmdt4fbqva56a9ncc6e2uj5ehgi7fci6.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplayerTictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpHMx6fsU4HdCHD-f8m3BKi5CFRALNRQ0',
    appId: '1:805174990201:web:2cb027ac2a2d3168734ba8',
    messagingSenderId: '805174990201',
    projectId: 'multiplayer-tictactoe-c4744',
    authDomain: 'multiplayer-tictactoe-c4744.firebaseapp.com',
    storageBucket: 'multiplayer-tictactoe-c4744.firebasestorage.app',
    measurementId: 'G-KCDV2R5B5L',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFU-rLk8xHVM3w-8gVv8LFzZyQduppqsc',
    appId: '1:805174990201:ios:95e8d1d92e2a4824734ba8',
    messagingSenderId: '805174990201',
    projectId: 'multiplayer-tictactoe-c4744',
    storageBucket: 'multiplayer-tictactoe-c4744.firebasestorage.app',
    iosClientId: '805174990201-tmdt4fbqva56a9ncc6e2uj5ehgi7fci6.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplayerTictactoe',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1Ka7Epyz4QJ2b7pz7pOss7Hj4bTwikM',
    appId: '1:805174990201:android:ae3b5d7c34fae808734ba8',
    messagingSenderId: '805174990201',
    projectId: 'multiplayer-tictactoe-c4744',
    storageBucket: 'multiplayer-tictactoe-c4744.firebasestorage.app',
  );

}